### ISSUE TITLE
baked in !so for shoutout of other users

### ISSUE THREAD

**Issue by VinylVault** [MitchellHarrison/python-twitch-chatbot#18]
an important feature for a lot of streamers is a ShoutOut command, it should be limited use, a user can't !so themselves but the streamer should define what level of user can use it - all - vip - mod

**Comment by VinylVault** [comment]
i think there should be a rejection message if users tries to shout themselves out, and maybe a configurable timeout?

**Comment by MitchellHarrison** [comment]
need to send this on bot startup to get tags `< CAP REQ :twitch.tv/tags`

**Comment by MitchellHarrison** [comment]
Done. Users are unable to shoutout themselves, and bot corrects for users that haven't streamed in six months.
