### ISSUE TITLE
Follow and Subscription notifications

### ISSUE THREAD

**Issue by VinylVault** [MitchellHarrison/python-twitch-chatbot#21]
Baked in follow and subscription notifications, rather than relying on a 3rd party solution, like streamlabs or streamelements

**Comment by MitchellHarrison** [comment]
`app.py` successfully creates EventSub subscriptions using an ngrok address. The subscriptions are listed but no data seems to flow. #42 is tracking that. Closing this one since #42 will cover it, and the subscriptions themselves are created.
