### ISSUE TITLE
Feature Request: !rank command

### ISSUE THREAD

**Issue by absenth** [MitchellHarrison/python-twitch-chatbot#4]
As a user, I should be able to type `!rank` and get my overall chat rank from the bot.  It might also be fun to include sub ranks such as... `!rank discord` to see where I as a user rank in executing the `!discord` command.

**Comment by ghost** [comment]
i second this

**Comment by MitchellHarrison** [comment]
For now, I'll keep this issue to implementing the rank of a user on a "total chat messages sent" leaderboard. I love the idea of command-specific leaderboards, but that'll come after the initial implementation. Should be just a slightly different SQL query, but I'll make that its own ticket. Awesome idea!

**Comment by MitchellHarrison** [comment]
Command works. Ranks on total number of messages sent in chat.
