### ISSUE TITLE
Feature Request !FeatureRequest command

### ISSUE THREAD

**Issue by absenth** [MitchellHarrison/python-twitch-chatbot#5]
As a User, it might be awesome if typing something like.... `!featurerequest add a featurerequest command that allows a user to define a new github issue with the feature request label on the chat bot project`

**Comment by VinylVault** [comment]
also an !addissue command

**Comment by MitchellHarrison** [comment]
> 
> 
> As a User, it might be awesome if typing something like.... `!featurerequest add a featurerequest command that allows a user to define a new github issue with the feature request label on the chat bot project`

I'm super into this idea. Although I'm not sure about direct GitHub integration. Perhaps a table in the database for it? I'm worried that people "testing" the bot could cause a flood of unhelpful issues that I need to parse. Do you see any way around this?

**Comment by MitchellHarrison** [comment]
> 
> 
> also an !addissue command

What would the difference be there? Just whether or not it's flagged with a _feature request_ label?

**Comment by MitchellHarrison** [comment]
Done! For now, it simply stores the requests in the SQLite database for me to parse through later. Connecting to GH directly seems awesome, but I'm weary of spam. For now, it works as I want it to. Issue closed!
