### ISSUE TITLE
Refactor app to align with goals of the overarching project.

### ISSUE THREAD

**Issue by matthew-dawson** [MitchellHarrison/python-twitch-chatbot#8]
- [x] Chat bot should join a specified chat room.
- [x] Chat bot should parse incoming messages for commands /emotes.
- [x] Chat bot should send messages in response to various commands parsed.
- [x] Chat bot should log command usage events to a database.

### Commands:
**Admin**
- [x] !addcommand - Adds a command to the database of known commands.
- [x] !editcommand - Edits an existing command within the database.
- [x] !delcommand - Deletes an existing command within the database.

**User/text**
- [x] !followage - 
- [x] !uptime -
- [x] !commands - Lists the commands available within the database.
- [x] !rank - 
- [x] !joke - Utilizes a third-party API to return a random joke.

**Comment by MitchellHarrison** [comment]
This is a very helpful summary of the work laid out on stream today. Fortunately, many are already working, if not exactly how I want them to. There's going to have to be some big changes to this repo, as it will likely just become a home for the chatbot, but all of these are definitely planned. Will create individual issues for the broken/non-existent commands.  
  
Big help, thanks!

**Comment by matthew-dawson** [comment]
You can even reference this issue within the new issues you create, in order to better track progress.

**Comment by MitchellHarrison** [comment]
Everything here is working. There's still one slight change to !rank that needs to come with #10 , and I'm working that now. For now, I'll close this one and open new issues when they arise. Thanks again!
